Task 2. 
Student_data = {"st-1":{"Maths":85,"Urdu":70,"Sindhi":40,"Chemistry":90,"Physics":60},
               "st-2":{"Maths":70,"Urdu":75,"Sindhi":40,"Chemistry":90,"Physics":60},
               "st-3":{"Maths":80,"Urdu":70,"Sindhi":95,"Chemistry":90,"Physics":60},
               "st-4":{"Maths":80,"Urdu":70,"Sindhi":50,"Chemistry":85,"Physics":60},
               "st-5":{"Maths":80,"Urdu":75,"Sindhi":40,"Chemistry":90,"Physics":60}}
1. Find Max and Min marks in every subject with StudentID.
2. Find Max and Min marks of every student with subject name.
3. Rank students on their total marks.

In [3]:
import numpy as np

In [52]:
Student_data = {"st-1":{"Maths":85,"Urdu":70,"Sindhi":40,"Chemistry":90,"Physics":60},
                "st-2":{"Maths":70,"Urdu":75,"Sindhi":40,"Chemistry":90,"Physics":60},
                "st-3":{"Maths":80,"Urdu":70,"Sindhi":95,"Chemistry":90,"Physics":60},
                "st-4":{"Maths":80,"Urdu":70,"Sindhi":50,"Chemistry":85,"Physics":60},
                "st-5":{"Maths":80,"Urdu":75,"Sindhi":40,"Chemistry":90,"Physics":60}}
Student_array=np.array([list(marks.values())for marks in Student_data.values()])
Student_ids=np.array([ids for ids in Student_data])
Subjects=np.array(list(Student_data["st-1"].keys()))
total_marks = Student_array.sum(axis = 1)
ranking = total_marks.argsort()[::-1]
max_sub_student = Student_array.argmax(axis = 1)
for rank, index in enumerate(ranking, start=1):
    student = Student_array[index]
    print(f"Rank: {rank}")
    print(f"Student_ID: {Student_ids[index]}")
    max_sub = max_sub_student[index]
    print(f"Max subject: {Subjects[max_sub]}\nMax Marks: {student[max_sub]}")
    print("_"*10)

Rank: 1
Student_ID: st-3
Max subject: Sindhi
Max Marks: 95
__________
Rank: 2
Student_ID: st-5
Max subject: Chemistry
Max Marks: 90
__________
Rank: 3
Student_ID: st-4
Max subject: Chemistry
Max Marks: 85
__________
Rank: 4
Student_ID: st-1
Max subject: Chemistry
Max Marks: 90
__________
Rank: 5
Student_ID: st-2
Max subject: Chemistry
Max Marks: 90
__________


In [39]:
print(total_marks)
print(Student_array)
print(Student_ids)
print(ranking)
print(Subjects)
print(Student_array.argmax(axis = 1))
print(Student_array.argsort())

[345 335 395 345 345]
[[85 70 40 90 60]
 [70 75 40 90 60]
 [80 70 95 90 60]
 [80 70 50 85 60]
 [80 75 40 90 60]]
['st-1' 'st-2' 'st-3' 'st-4' 'st-5']
[2 4 3 0 1]
['Maths' 'Urdu' 'Sindhi' 'Chemistry' 'Physics']
[3 3 2 3 3]
[[2 4 1 0 3]
 [2 4 0 1 3]
 [4 1 0 3 2]
 [2 4 1 0 3]
 [2 4 1 0 3]]
