In [2]:
import numpy as np

In [4]:
my_array = np.array([2,4,6,7,8,7,45,3,2,12,33])

print(my_array)

[ 2  4  6  7  8  7 45  3  2 12 33]


In [4]:
list_1 = [1,2,3,4,5]
list_1 = np.array(list_1,dtype = np.float64)

In [5]:
list_1

array([1., 2., 3., 4., 5.])

In [7]:
list_2 = [1,2,3,4,5]
list_2 = np.array(list_1,dtype = np.int8)
list_2

array([1, 2, 3, 4, 5], dtype=int8)

In [10]:
my_multi_array = np.array([[1,2,3],['a','b','c'],[True,False,True]])
my_multi_array

array([['1', '2', '3'],
       ['a', 'b', 'c'],
       ['True', 'False', 'True']], dtype='<U21')

In [12]:
np.linspace(0,1,15)

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
print(np.arange(1,10))
np.arange(2,20,2)

[1 2 3 4 5 6 7 8 9]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
myarray = np.arange(1,100)
myarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
myarray.size

99

In [18]:
len(myarray)

99

In [27]:
myarray.dtype

dtype('int64')

In [31]:
np.random.randint(1,50, size=10)

array([43, 33, 25, 19, 19, 42,  9, 21,  7, 48], dtype=int32)

In [33]:
np.random.choice(['HEAD','TAIL'])

np.str_('TAIL')

In [35]:
np.random.choice(['HEAD','TAIL'],size = 20)

array(['TAIL', 'TAIL', 'TAIL', 'HEAD', 'TAIL', 'TAIL', 'HEAD', 'HEAD',
       'HEAD', 'HEAD', 'HEAD', 'TAIL', 'HEAD', 'TAIL', 'HEAD', 'TAIL',
       'HEAD', 'TAIL', 'TAIL', 'TAIL'], dtype='<U4')

In [11]:
np.array([1,23,6,6,7,89,9,5,4,44,90])

array([ 1, 23,  6,  6,  7, 89,  9,  5,  4, 44, 90])

In [15]:
np.random.choice([1,10])

np.int64(1)

In [7]:
np.arange(1,5).dtype = np.int8

In [ ]:
list= [[1,3,5],[4,8,4,],[3,8,2]]


In [13]:
studentdata = [["MAth","science","english","urdu","sindhi"],
               [50,60,70,80,40],
               [30,70,80,40,50],
               [20,60,40,70,90],
               [90,40,80,60,50],
               [70,50,30,90,20]]
subjects = studentdata.pop(0)
array1=np.array(studentdata)

max_subject = array1.argmax(axis=0)
print(max_subject)
max_student = array1.argmax(axis=1)
print(max_student)

for i in range (0, len(subjects)):
    print (f"{subjects[i]}: Max marks: {studentdata[max_subject[i]],i}")



[3 1 1 4 2]
[3 2 4 0 3]
MAth: Max marks: ([90, 40, 80, 60, 50], 0)
science: Max marks: ([30, 70, 80, 40, 50], 1)
english: Max marks: ([30, 70, 80, 40, 50], 2)
urdu: Max marks: ([70, 50, 30, 90, 20], 3)
sindhi: Max marks: ([20, 60, 40, 70, 90], 4)


In [3]:
initial_a=9000
profit = np.array([-0.10,0.20,0.80,-0.30,-0.40,-0.20,0.30,0.60,-0.10,0.20])
factor = profit + 1
#print(factor)
p_o_f = factor.prod()
amount = 9000*p_o_f
print(amount)
print(f"profit is {amount-initial_a}")
print(f"Amean: {profit.mean(): .2f}")

13205.812838400001
profit is 4205.812838400001
Amean:  0.10


In [4]:
gmean=np.pow(profit.prod(),1/len(factor))-1

C:\Users\afham\AppData\Local\Temp\ipykernel_16012\1492145057.py:1: RuntimeWarning: invalid value encountered in power
  gmean=np.pow(profit.prod(),1/len(factor))-1


In [22]:
profit.prod()

np.float64(-1.3824000000000007e-06)

Amean:  0.10


In [3]:
python_list = [1,2,3,4,5]
print(python_list)

[1, 2, 3, 4, 5]


In [37]:
ar_r = np.array([[1,3,4],    #two dimentional array
                 [2,4,6],
                 [3,5,7]])
print(ar_r.shape)
print(ar_r.size)
print(ar_r.ndim)
print(ar_r.dtype)
ar_r.astype(float)

(3, 3)
9
2
int64


array([[1., 3., 4.],
       [2., 4., 6.],
       [3., 5., 7.]])

In [38]:
zero=np.zeros((3,3))
zero+5


array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [18]:
one=np.ones((3,2))
one

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
filled_a = np.full((2,2),5)
print(filled_a)

[[5 5]
 [5 5]]


In [45]:
arr=np.array([90,80,70,60,50])
print(np.min(arr))
np.max(arr)

50


np.int64(90)

In [46]:
np.mean(arr)

np.float64(70.0)

In [49]:
arr1=np.array([10,90,80,30,40])
arr1[3]  #access index number

np.int64(30)

In [10]:
#slicing
arr2=np.array([90,40,50,30,50,90,80])
print(arr2[0:7])
print(arr2[:3])
print(arr2[3:])
print(arr2[::2])  #every second element
print(arr2[::-1])  #reverse a list 

[90 40 50 30 50 90 80]
[90 40 50]
[30 50 90 80]
[90 50 50 80]
[80 90 50 30 50 40 90]


In [12]:
arr2[arr2>50]

array([90, 90, 80])